<?xml version="1.0" encoding="utf-8"?><Database Name="CarWorkshopDB" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\CarWorkshopDB.mdf;Integrated Security=True" SettingsObjectName="CarWorkshopSystem.My.MySettings" SettingsPropertyName="CarWorkshopDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="customerIC" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="passportNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="contactNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="race" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="serviceCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Customer_Car" Member="Cars" ThisKey="customerIC" OtherKey="customerIC" Type="Car" />
      <Association Name="Customer_Bill" Member="Bills" ThisKey="customerIC" OtherKey="customerIC" Type="Bill" />
      <Association Name="Customer_Appointment" Member="Appointments" ThisKey="customerIC" OtherKey="customerIC" Type="Appointment" />
      <Association Name="Customer_Review" Member="Reviews" ThisKey="customerIC" OtherKey="customerIC" Type="Review" />
      <Association Name="Customer_OnlineOrder" Member="OnlineOrders" ThisKey="customerIC" OtherKey="customerIC" Type="OnlineOrder" />
    </Type>
  </Table>
  <Table Name="dbo.ServiceCoupon" Member="ServiceCoupons">
    <Type Name="ServiceCoupon">
      <Column Name="serialNo" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="usage" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="expireDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="ServiceCoupon_Payment" Member="Payments" ThisKey="serialNo" OtherKey="serialNo" Type="Payment" />
    </Type>
  </Table>
  <Table Name="dbo.Car" Member="Cars">
    <Type Name="Car">
      <Column Name="carRegisterNo" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="carModel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="color" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="customerIC" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Car_JobSheet" Member="JobSheets" ThisKey="carRegisterNo" OtherKey="carRegisterNo" Type="JobSheet" />
      <Association Name="Customer_Car" Member="Customer" ThisKey="customerIC" OtherKey="customerIC" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bin" Member="Bins">
    <Type Name="Bin">
      <Column Name="binID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dStockID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="dStockName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="dStockQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dStockBinDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="dStockStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="binDisposalReason" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="supplierID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="supplierName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="supplierContact" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="supplierAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BillingRecord" Member="BillingRecords">
    <Type Name="BillingRecord">
      <Column Name="billNo" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="inventoryID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="billingAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="warrantyPeriod" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Bill_BillingRecord" Member="Bill" ThisKey="billNo" OtherKey="billNo" Type="Bill" IsForeignKey="true" />
      <Association Name="ItemStorage_BillingRecord" Member="ItemStorage" ThisKey="inventoryID" OtherKey="inventoryID" Type="ItemStorage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsedItems" Member="UsedItems">
    <Type Name="UsedItem">
      <Column Name="dStockID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dStockName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="dStockQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dStockBatchNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="dStockCategory" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="dStockArrivalDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="dStockCondition" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="dStockBrand" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="dStockDescription" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="dStockSpecification" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="dStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="dSupplier" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="dPrice" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="dType" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="billNo" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="billDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="totalAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="customerIC" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Bill_BillingRecord" Member="BillingRecords" ThisKey="billNo" OtherKey="billNo" Type="BillingRecord" />
      <Association Name="Bill_Payment" Member="Payments" ThisKey="billNo" OtherKey="billNo" Type="Payment" />
      <Association Name="Bill_OnlineOrder" Member="OnlineOrders" ThisKey="billNo" OtherKey="billNo" Type="OnlineOrder" />
      <Association Name="Bill_JobSheet" Member="JobSheets" ThisKey="billNo" OtherKey="billNo" Type="JobSheet" />
      <Association Name="Customer_Bill" Member="Customer" ThisKey="customerIC" OtherKey="customerIC" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WarrantyClaim" Member="WarrantyClaims">
    <Type Name="WarrantyClaim">
      <Column Name="warrantyClaimID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="warrantyClaimDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="warrantyClaimTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="reason" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="paymentID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="inventoryID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Payment_WarrantyClaim" Member="Payment" ThisKey="paymentID" OtherKey="paymentID" Type="Payment" IsForeignKey="true" />
      <Association Name="ItemStorage_WarrantyClaim" Member="ItemStorage" ThisKey="inventoryID" OtherKey="inventoryID" Type="ItemStorage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="appointmentID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="appointmentDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="appointmentTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="problem" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="appointmentStatus" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="customerIC" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="staffIC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Customer_Appointment" Member="Customer" ThisKey="customerIC" OtherKey="customerIC" Type="Customer" IsForeignKey="true" />
      <Association Name="Staff_Appointment" Member="Staff" ThisKey="staffIC" OtherKey="staffIC" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Review" Member="Reviews">
    <Type Name="Review">
      <Column Name="reviewID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerIC" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="customerName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="workshopBranch" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="serviceRating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="customerComment" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="reviewDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="serviceType" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Customer_Review" Member="Customer" ThisKey="customerIC" OtherKey="customerIC" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="paymentID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="discount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="paymentAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="paymentChange" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="paymentDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="paymentTime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="paymentMethod" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="creditNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="billNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="serialNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Payment_WarrantyClaim" Member="WarrantyClaims" ThisKey="paymentID" OtherKey="paymentID" Type="WarrantyClaim" />
      <Association Name="Bill_Payment" Member="Bill" ThisKey="billNo" OtherKey="billNo" Type="Bill" IsForeignKey="true" />
      <Association Name="ServiceCoupon_Payment" Member="ServiceCoupon" ThisKey="serialNo" OtherKey="serialNo" Type="ServiceCoupon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="staffIC" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="position" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="contactNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="race" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="emplomentDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="staffPic" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Staff_Appointment" Member="Appointments" ThisKey="staffIC" OtherKey="staffIC" Type="Appointment" />
      <Association Name="Staff_JobSheet" Member="JobSheets" ThisKey="staffIC" OtherKey="staffIC" Type="JobSheet" />
    </Type>
  </Table>
  <Table Name="dbo.ItemStorage" Member="ItemStorages">
    <Type Name="ItemStorage">
      <Column Name="inventoryID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stockName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="stockQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="stockBatchNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="stockCategory" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stockArrivalDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="stockCondition" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stockBrand" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stockDescription" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="stockSpecification" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="stockStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stockType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stockSupplier" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="stockPrice" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="stockImage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="stockPath" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="ItemStorage_BillingRecord" Member="BillingRecords" ThisKey="inventoryID" OtherKey="inventoryID" Type="BillingRecord" />
      <Association Name="ItemStorage_WarrantyClaim" Member="WarrantyClaims" ThisKey="inventoryID" OtherKey="inventoryID" Type="WarrantyClaim" />
      <Association Name="ItemStorage_OnlineOrder" Member="OnlineOrders" ThisKey="inventoryID" OtherKey="inventoryID" Type="OnlineOrder" />
    </Type>
  </Table>
  <Table Name="dbo.OnlineOrder" Member="OnlineOrders">
    <Type Name="OnlineOrder">
      <Column Name="orderID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="customerPhoneNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="customerIC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="billNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="creditCardInfo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="inventoryID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="stockName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="orderDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="workshopBranch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="workshopAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="orderStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="paymentMethod" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="orderCost" Type="System.Decimal" DbType="SmallMoney" CanBeNull="true" />
      <Column Name="amountOrdered" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bill_OnlineOrder" Member="Bill" ThisKey="billNo" OtherKey="billNo" Type="Bill" IsForeignKey="true" />
      <Association Name="Customer_OnlineOrder" Member="Customer" ThisKey="customerIC" OtherKey="customerIC" Type="Customer" IsForeignKey="true" />
      <Association Name="ItemStorage_OnlineOrder" Member="ItemStorage" ThisKey="inventoryID" OtherKey="inventoryID" Type="ItemStorage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Workshop" Member="Workshops">
    <Type Name="Workshop">
      <Column Name="workshopID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="workshopRegistrationNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="workshopEmail" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="workshopState" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="workshopAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="workshopContact" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="workshopOD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="workshopStatus" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JobSheet" Member="JobSheets">
    <Type Name="JobSheet">
      <Column Name="jobSheetNo" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="jobSheetDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="jobSheetType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="staffIC" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="carRegisterNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="mileage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="problem" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="timeIn" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="timeOut" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="billNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="nextMileage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bill_JobSheet" Member="Bill" ThisKey="billNo" OtherKey="billNo" Type="Bill" IsForeignKey="true" />
      <Association Name="Car_JobSheet" Member="Car" ThisKey="carRegisterNo" OtherKey="carRegisterNo" Type="Car" IsForeignKey="true" />
      <Association Name="Staff_JobSheet" Member="Staff" ThisKey="staffIC" OtherKey="staffIC" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
</Database>